<?php
// Debug script for complaint functionality on Render.com
// Upload this file to your Render.com instance and access it via browser

error_reporting(E_ALL);
ini_set('display_errors', 1);

header('Content-Type: text/plain');

echo "=== COMPLAINT SYSTEM DEBUG REPORT ===\n\n";

// Test 1: Environment Variables
echo "1. ENVIRONMENT VARIABLES:\n";
echo "DB_HOST: " . (getenv('DB_HOST') ?: 'NOT SET') . "\n";
echo "DB_PORT: " . (getenv('DB_PORT') ?: 'NOT SET') . "\n";
echo "DB_NAME: " . (getenv('DB_NAME') ?: 'NOT SET') . "\n";
echo "DB_USER: " . (getenv('DB_USER') ?: 'NOT SET') . "\n";
echo "DB_PASSWORD: " . (getenv('DB_PASSWORD') ? 'SET' : 'NOT SET') . "\n";
echo "DB_TYPE: " . (getenv('DB_TYPE') ?: 'NOT SET') . "\n";
echo "DATABASE_URL: " . (getenv('DATABASE_URL') ? 'SET' : 'NOT SET') . "\n\n";

// Test 2: Database Connection
echo "2. DATABASE CONNECTION:\n";
try {
    require_once __DIR__ . '/src/config/database.php';
    $db = new Database();
    $conn = $db->connect();
    echo "✓ Database connection: SUCCESS\n";
    echo "✓ Database type: " . $conn->getAttribute(PDO::ATTR_DRIVER_NAME) . "\n";
} catch (Exception $e) {
    echo "✗ Database connection: FAILED\n";
    echo "✗ Error: " . $e->getMessage() . "\n";
    echo "✗ Error Code: " . $e->getCode() . "\n";
    echo "✗ Error File: " . $e->getFile() . ":" . $e->getLine() . "\n\n";
    exit(1);
}

// Test 3: Check Required Tables
echo "\n3. TABLE EXISTENCE CHECK:\n";
$tables = ['users', 'complaints', 'complaint_responses', 'products', 'orders'];
foreach ($tables as $table) {
    try {
        $stmt = $conn->query("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = '$table')");
        $exists = $stmt->fetchColumn();
        echo ($exists ? "✓" : "✗") . " Table '$table': " . ($exists ? "EXISTS" : "MISSING") . "\n";
    } catch (Exception $e) {
        echo "✗ Table '$table': ERROR - " . $e->getMessage() . "\n";
    }
}

// Test 4: Test Complaint Controller
echo "\n4. COMPLAINT CONTROLLER TEST:\n";
try {
    require_once __DIR__ . '/src/controllers/ComplaintController.php';
    $controller = new ComplaintController();
    echo "✓ ComplaintController instantiated successfully\n";
    
    // Test getting complaint types
    $types = $controller->getComplaintTypes();
    echo "✓ Complaint types loaded: " . count($types) . " types\n";
    
    // Test getting available respondents
    $respondents = $controller->getAvailableRespondents(1);
    echo "✓ Available respondents: " . count($respondents) . " users\n";
    
} catch (Exception $e) {
    echo "✗ ComplaintController: FAILED\n";
    echo "✗ Error: " . $e->getMessage() . "\n";
    echo "✗ Error Code: " . $e->getCode() . "\n";
    echo "✗ Error File: " . $e->getFile() . ":" . $e->getLine() . "\n";
}

// Test 5: Test Complaint Creation
echo "\n5. COMPLAINT CREATION TEST:\n";
try {
    $testData = [
        'complainant_id' => 1,
        'respondent_id' => 2,
        'complaint_type' => 'product_issue',
        'subject' => 'Test Complaint - ' . date('Y-m-d H:i:s'),
        'description' => 'This is a test complaint generated by the debug script.',
        'order_id' => null,
        'product_id' => null
    ];
    
    $result = $controller->createComplaint($testData);
    
    if ($result['success']) {
        echo "✓ Test complaint created successfully\n";
        echo "✓ Complaint ID: " . $result['complaint_id'] . "\n";
        echo "✓ Message: " . $result['message'] . "\n";
    } else {
        echo "✗ Test complaint creation failed\n";
        echo "✗ Error: " . $result['message'] . "\n";
    }
    
} catch (Exception $e) {
    echo "✗ Complaint creation: FAILED\n";
    echo "✗ Error: " . $e->getMessage() . "\n";
    echo "✗ Error Code: " . $e->getCode() . "\n";
    echo "✗ Error File: " . $e->getFile() . ":" . $e->getLine() . "\n";
}

// Test 6: Check User Session
echo "\n6. SESSION INFORMATION:\n";
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
echo "Session ID: " . session_id() . "\n";
echo "User ID in session: " . ($_SESSION['user_id'] ?? 'NOT SET') . "\n";
echo "User role in session: " . ($_SESSION['user_role'] ?? 'NOT SET') . "\n";

// Test 7: Check File Permissions
echo "\n7. FILE PERMISSIONS:\n";
$files = [
    'src/config/database.php',
    'src/controllers/ComplaintController.php',
    'src/models/Complaint.php',
    'src/models/Users.php',
    'public/file-complaint.php'
];

foreach ($files as $file) {
    if (file_exists(__DIR__ . '/' . $file)) {
        $perms = substr(sprintf('%o', fileperms(__DIR__ . '/' . $file)), -4);
        echo "✓ $file: $perms\n";
    } else {
        echo "✗ $file: MISSING\n";
    }
}

// Test 8: PHP Extensions
echo "\n8. PHP EXTENSIONS:\n";
$required_extensions = ['pdo', 'pdo_pgsql', 'pgsql', 'json', 'mbstring'];
foreach ($required_extensions as $ext) {
    echo (extension_loaded($ext) ? "✓" : "✗") . " Extension '$ext': " . (extension_loaded($ext) ? "LOADED" : "MISSING") . "\n";
}

echo "\n=== DEBUG COMPLETE ===\n";
echo "If you see any ✗ marks above, those are the issues to fix.\n";
echo "Copy this entire output and share it for further assistance.\n";
?>
